package db2dialect

import (
	"database/sql"
	"fmt"
	"reflect"
	"time"

	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect"
	"github.com/uptrace/bun/dialect/feature"
	"github.com/uptrace/bun/dialect/sqltype"
	"github.com/uptrace/bun/schema"
)

func init() {
	if Version() != bun.Version() {
		panic(fmt.Errorf("db2dialect and Bun must have the same version: v%s != v%s",
			Version(), bun.Version()))
	}
}

type Dialect struct {
	schema.BaseDialect

	tables   *schema.Tables
	features feature.Feature
}

func New(opts ...DialectOption) *Dialect {
	d := new(Dialect)
	d.tables = schema.NewTables(d)
	d.features = feature.CTE |
		feature.WithValues |
		feature.SelectExists |
		feature.CompositeIn |
		feature.OffsetFetch |
		feature.Identity

	for _, opt := range opts {
		opt(d)
	}

	return d
}

type DialectOption func(d *Dialect)

func WithoutFeature(other feature.Feature) DialectOption {
	return func(d *Dialect) {
		d.features = d.features.Remove(other)
	}
}

func (d *Dialect) Init(*sql.DB) {}

func (d *Dialect) Name() dialect.Name {
	return dialect.DB2
}

func (d *Dialect) Features() feature.Feature {
	return d.features
}

func (d *Dialect) Tables() *schema.Tables {
	return d.tables
}

func (d *Dialect) OnTable(table *schema.Table) {
	for _, field := range table.FieldMap {
		// Bun resolves CreateTableSQLType from UserSQLType/DiscoveredSQLType only
		// after OnTable returns, so an explicit `type:` tag must be preserved here.
		if field.UserSQLType != "" || field.CreateTableSQLType != "" {
			continue
		}
		field.DiscoveredSQLType = fieldSQLType(field)
	}
}

func (d *Dialect) IdentQuote() byte {
	return '"'
}

func (d *Dialect) DefaultVarcharLen() int {
	return 255
}

// DefaultSchema returns an empty schema so DB2 uses the current authorization ID.
func (d *Dialect) DefaultSchema() string {
	return ""
}

// AppendSequence emits the DB2 IDENTITY clause for autoincrement primary keys.
func (d *Dialect) AppendSequence(b []byte, _ *schema.Table, _ *schema.Field) []byte {
	return append(b, " GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)"...)
}

func (*Dialect) AppendTime(b []byte, tm time.Time) []byte {
	b = append(b, '\'')
	b = tm.UTC().AppendFormat(b, "2006-01-02 15:04:05.999999")
	b = append(b, '\'')
	return b
}

func (*Dialect) AppendBool(b []byte, v bool) []byte {
	if v {
		return append(b, '1')
	}
	return append(b, '0')
}

var (
	dateType      = reflect.TypeFor[Date]()
	timeOfDayType = reflect.TypeFor[TimeOfDay]()
	timestampType = reflect.TypeFor[Timestamp]()
	timeType      = reflect.TypeFor[time.Time]()

	smallIntType         = reflect.TypeFor[SmallInt]()
	smallIntBoolType     = reflect.TypeFor[SmallIntBool]()
	nullSmallIntType     = reflect.TypeFor[NullSmallInt]()
	nullSmallIntBoolType = reflect.TypeFor[NullSmallIntBool]()
)

// fieldSQLType maps the SQL type bun discovers from the Go field type to the
// closest DB2-native type. DB2 has no usable BOOLEAN column type on older
// versions, so booleans are stored as SMALLINT.
func fieldSQLType(field *schema.Field) string {
	// The helper types in types.go carry DB2 semantics that bun cannot infer:
	// the SMALLINT ones would be discovered as INTEGER/VARCHAR, and the
	// time-based ones as VARCHAR because they are named types, not time.Time.
	switch field.IndirectType {
	case smallIntType, smallIntBoolType, nullSmallIntType, nullSmallIntBoolType:
		return sqltype.SmallInt
	case dateType:
		return "DATE"
	case timeOfDayType:
		return "TIME"
	case timestampType:
		return sqltype.Timestamp
	}

	if field.IndirectType.Kind() == reflect.Struct && field.IndirectType.ConvertibleTo(timeType) {
		return sqltype.Timestamp
	}

	switch field.DiscoveredSQLType {
	case sqltype.Boolean:
		return sqltype.SmallInt
	default:
		return field.DiscoveredSQLType
	}
}
